### PR TITLE
Added signal declaration to the snippets

### PR DESCRIPTION
**Pull request by valerionew**

### CODE REVIEW

**Comment by GlenNicholls** [comment]
I need to review this and compare it to other snippets. I’m somewhat okay, but I need to go through everything I wrote again to make sure it makes sense to add one for a signal declaration and ensure this is consistent

**Comment by GlenNicholls** [comment]
This IMO should be more descriptive. For example, look at the following:

``` json
"Alias": {
		"prefix": "alias",
		"body": [
			"alias ${1:<name>} : ${2:<subtype>} is ${3:<object_name>};",
			"$0"
		],
		"description": "alias declaration"
	},
```

It'd be nice if you also replicated signal but for variable as well.

**Comment by GlenNicholls** [comment]
I'm not allowed to approve this, so you might want to ping the maintainer.

**Comment by kraigher** [comment]
@GlenNicholls I gave you write permissions to the repository if you want to make these kind of changes.

**Pull request merged**
